"""
backtest/synthetic_book.py
--------------------------
Constructs a synthetic 50-level order book from a single 1-minute kline row.

The output format is intentionally identical to ``state.local_book`` used by
the live system so that the backtest can pass it directly to
``AnalysisEngine._build_levels(book["bids"], book["asks"])`` without any
adapter layer.

This module is stateless and contains no I/O.  ``fetch_klines()`` is NOT
called here — the caller (``backtest/signals.py``) fetches the full kline
DataFrame once and passes individual rows to ``build_synthetic_book()``.
"""

from config_parameters import N_LEVELS, VOLUME_DECAY_FACTOR


def build_synthetic_book(row) -> dict:
    """
    Build a synthetic 50-level order book dict from a single kline row.

    The construction follows three steps:

    **Step 1 — Spread reconstruction**
        The candle's high-low range is used as a proxy for the full bid-ask
        spread observed during that minute.  ``close`` anchors the mid-price
        (last traded price — best single-point estimate of where the market
        was at candle close).

        ``half_spread  = (high - low) / 2``
        ``best_bid     = close - half_spread``
        ``best_ask     = close + half_spread``
        ``tick_size    = high - low``   (= best_ask - best_bid)

    **Step 2 — Symmetric depth ladder**
        ``N_LEVELS`` price levels are generated by stepping away from the
        best bid / best ask in increments of ``tick_size``.  Volume at each
        level decays exponentially (``VOLUME_DECAY_FACTOR ** i``) to replicate
        the natural thinning of liquidity away from the top of book, where
        market makers post the most competitive size.

        At ``VOLUME_DECAY_FACTOR = 0.80``:
          level 0  →  base_volume × 1.000  (best bid / ask)
          level 1  →  base_volume × 0.800
          level 5  →  base_volume × 0.328
          level 10 →  base_volume × 0.107
          level 49 →  base_volume × ~0.000  (negligible)

    **Step 3 — OBI asymmetry injection**
        A purely symmetric book produces OBI = 0 at every level, which means
        ``micro_price == mid_price`` and no signal is ever generated.
        The kline's taker volume split is used to break this symmetry:

        ``buy_ratio  = taker_buy_base_vol / volume``  ∈ (0, 1)
        ``sell_ratio = 1 - buy_ratio``

        Each bid quantity is multiplied by ``2 × buy_ratio`` and each ask
        quantity by ``2 × sell_ratio``.  The factor of 2 ensures total
        volume per level is preserved:
          ``bq_new + aq_new = qty × 2 × buy_ratio + qty × 2 × sell_ratio``
                           ``= 2 × qty``   ✓  (unchanged from symmetric book)

        After injection:
          ``OBI         = 2 × buy_ratio − 1``
                         (equals ``obi_proxy`` used in HMM features exactly)
          ``micro_price = close + half_spread × (2 × buy_ratio − 1)``

        Concrete examples (close = 85 000, half_spread = 50):
          buy_ratio = 0.5  →  OBI =  0.0,  micro_price = 85 000.00  (neutral)
          buy_ratio = 0.7  →  OBI = +0.4,  micro_price = 85 020.00  (BUY signal)
          buy_ratio = 0.3  →  OBI = −0.4,  micro_price = 84 980.00  (SELL signal)

    Parameters
    ----------
    row : pd.Series
        A single row from the DataFrame returned by ``backtest.data.fetch_klines()``.
        Required columns: ``high``, ``low``, ``close``, ``volume``,
        ``taker_buy_base_vol``.

    Returns
    -------
    dict
        ``{"bids": {price_str: qty_str, …}, "asks": {price_str: qty_str, …}}``
        Each dict contains exactly ``N_LEVELS`` entries.
        String keys and values match the exact format of ``state.local_book``
        consumed by ``AnalysisEngine._build_levels()``.
    """
    high = float(row["high"])
    low = float(row["low"])
    close = float(row["close"])
    volume = float(row["volume"])
    taker_buy_base_vol = float(row["taker_buy_base_vol"])

    # ------------------------------------------------------------------
    # Step 1 — Spread reconstruction
    # Use the intra-bar high-low range as a proxy for the full bid-ask
    # spread.  close is a better anchor than (high+low)/2 because it
    # reflects where the market actually settled at candle close.
    # ------------------------------------------------------------------
    half_spread = (high - low) / 2.0
    synthetic_best_bid = close - half_spread
    synthetic_best_ask = close + half_spread
    tick_size = high - low  # == synthetic_best_ask - synthetic_best_bid

    # ------------------------------------------------------------------
    # Step 2 — Symmetric depth ladder
    # Spread base_volume evenly across levels as the starting point,
    # then apply exponential decay so deeper levels carry less liquidity.
    # ------------------------------------------------------------------
    base_volume = volume / N_LEVELS
    bids: dict[str, str] = {}
    asks: dict[str, str] = {}

    for i in range(N_LEVELS):
        qty = base_volume * (VOLUME_DECAY_FACTOR**i)
        bids[f"{synthetic_best_bid - i * tick_size:.2f}"] = f"{qty:.8f}"
        asks[f"{synthetic_best_ask + i * tick_size:.2f}"] = f"{qty:.8f}"

    # ------------------------------------------------------------------
    # Step 3 — OBI asymmetry injection
    # Rescale bid and ask quantities using the taker buy/sell split so
    # that OBI != 0 and micro_price tilts toward the thinner side.
    # The factor of 2 preserves total volume per level after the split
    # because: 2*buy_ratio + 2*sell_ratio = 2*(buy_ratio + sell_ratio) = 2.
    # Falls back to a neutral 50/50 split if volume is zero.
    # ------------------------------------------------------------------
    buy_ratio = (taker_buy_base_vol / volume) if volume > 0 else 0.5
    sell_ratio = 1.0 - buy_ratio

    bids = {p: f"{float(q) * 2.0 * buy_ratio:.8f}" for p, q in bids.items()}
    asks = {p: f"{float(q) * 2.0 * sell_ratio:.8f}" for p, q in asks.items()}

    return {"bids": bids, "asks": asks}
